# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='classroom name', max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='classroom description', max_length=300, verbose_name='Classroom description')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='school name', max_length=150, verbose_name='School name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='student first name', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='student last name', max_length=50, verbose_name='Last Name')),
                ('classroom', models.ForeignKey(blank=True, help_text='student classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='enroll.Classroom', verbose_name='related Classroom')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(help_text='school which classroom belongs', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='enroll.School', verbose_name='related School'),
        ),
    ]
